### ISSUE TITLE
Changing __sidebar_width__ in style.ini or style.local.ini has no effect

### ISSUE THREAD

**Issue by bgedik** [ryanwmoore/dokutwitterbootstrap#2]
As the title says.

**Comment by Floffyko** [comment]
Can you please say me if you solve this problem? Thanks a lot.

**Comment by selfthinker** [comment]
The problem cannot have been solved because this template doesn't use a `style.ini`. (All templates are required to use one but unfortunately there are a couple which don't do that.)
